[package]
name = "rocketsim_rs"
description = "Rust bindings for the RocketSim project"
version = "0.11.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/VirxEC/rocketsim-rs"
exclude = [".git*", "CMake*", "collision_meshes", "examples", "rustfmt.toml"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
autocxx = "0.25.0"
cxx = { version = "1.0.83", features = ["c++20"] }
glam = { version = "0.23.0", optional = true }

[build-dependencies]
glob = "0.3.0"
autocxx-build = "0.25.0"
miette = { version = "5", features = ["fancy"] }

[profile.release]
lto = true

[features]
default = ["glam"]
glam = ["dep:glam"]
rlbot = ["glam"]

[target.'cfg(not(any(target_arch = "x86", target_arch = "x86_64")))'.dependencies]
# use glam with experimental support for portable SIMD when not running on x86
# architectures
glam = { version = "0.23.0", optional = true, features = ["core-simd"] }

[dev-dependencies]
rand = "0.8.5"
