[package]
name = "rocketsim_rs"
version = "0.1.0"
edition = "2021"
publish = false
exclude = [".git*", "*.vcxproj", "assets"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
autocxx = { path = "../autocxx" }
cxx = { version = "1.0.83", features = ["c++17"] }

[build-dependencies]
glob = "0.3.0" 
autocxx-build = { path = "../autocxx/gen/build" }
miette = { version = "5", features = ["fancy"] }

[profile.release]
lto = true
