[package]
name = "rocketsim_rs"
description = "Rust bindings for the RocketSim project"
version = "0.1.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/VirxEC/rocketsim-rs"
exclude = [".git*", "*.vcxproj", "assets", "examples", "rustfmt.toml"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
autocxx = "0.24.0"
cxx = { version = "1.0.83", features = ["c++17"] }
glam = { version = "0.22.0", optional = true }

[build-dependencies]
glob = "0.3.0" 
autocxx-build = "0.24.0"
miette = { version = "5", features = ["fancy"] }

[features]
default = ["glam"]
glam = ["dep:glam"]

[profile.release]
lto = true
strip = true
panic = "abort"
